rename EmptySlotsMeta -> ContextVarsRegistryMeta
Because it gives a slightly better exception message in some cases.

E.g, instead of this:

    TypeError: 'EmptySlotsMeta' object is not iterable

now there is this:

    TypeError: 'ContextVarsRegistryMeta' object is not iterable